### ISSUE TITLE
ResponseError:{"error":"Sign in to confirm you’re not a bot"}

### ISSUE THREAD

**Issue by paka9999** [iBicha/UnityYoutubePlayer#132]
System.Exception: HTTP/1.1 500 Internal Server Error
ResponseError:{"error":"Sign in to confirm you’re not a bot"}

I used version 2.x.x of UnityYoutubePlayer with yt-dlp. But recently, due to a captcha verification issue, videos were not playing correctly, so I updated to version 3.3.0. However, the authentication issue is still occurring. Is there a solution?

This happens intermittently!

Please help me to solve this issue 😥

**Comment by iBicha** [comment]
Hello, this is basically the same issue as #129 
YouTube has been making changes in order to prevent playing videos outside of their website. This includes Invidious, yt-dlp, and others.
Right now, only a few instances seem to be working https://api.invidious.io
There's unfortunately not a lot that can be done right now (until a fix is implemented)
Closing in favor of #129
