### ISSUE TITLE
How to get highest quality? This gets only "720p".

### ISSUE THREAD

**Issue by Frozia00** [iBicha/UnityYoutubePlayer#23]
I have a problem about downloading of 1080p or higher quality videos.

**Comment by iBicha** [comment]
Youtube does not have videos higher than 720p in a single file. 1080p and higher are split in two files, for audio and video.
They do this because the audio for 1080p and higher is the same, to avoid duplicating the audio data, they share it across these higher quality files.
This is an issue for Unity, because first, the audio format usually not compatible with AudioSource component, and second, this will require additional sync mechanism to keep audio and video playing without a delay.
So for simplicity, this project just plays the highest quality available which is in a single file, which is usually 720p. But arguably you can modify this lib to make it go higher.
I hope this explains things.

**Comment by iBicha** [comment]
As explained, 720p is usually the highest available in a single file, that is compatible with Unity's video player. Higher formats will require alot of workarounds to support other container types (e.g. webm) and to synchronize potentially two streams (one for audio, and one for video). All of that is out of scope for now. Closing.
