### ISSUE TITLE
Is this package reliable in production stage ?

### ISSUE THREAD

**Issue by zicas2000** [iBicha/UnityYoutubePlayer#34]
Hi @iBicha 
Just asking about this package reliability in case of using it in production stage ,as I intend to use it in app estimated to be used by 50000 users concurrently.

**Comment by iBicha** [comment]
If you want my opinion, at 50000 concurrent users, **no package / solution for playing youtube is reliable**. Anything that plays youtube videos outside of the youtube website (or the embedded iframe) risks breaking at any moment if youtube make an update, because all of the packages (including youtube-dl, used in this repo) rely on parsing a webpage instead of a web API.
At that scale, I would suggest to use a different hosting entirely other youtube, to host and serve your files.
If you still want to use youtube, you should host [youtube-dl-server](https://github.com/iBicha/youtube-dl-server) yourself and scale it appropriately, because using the free instance will not be enough.
