### ISSUE TITLE
how can choose Quality on youtube video

### ISSUE THREAD

**Issue by mhadji05** [iBicha/UnityYoutubePlayer#6]
how can i choose the quality video plays?

![image](https://user-images.githubusercontent.com/22151801/65335420-0fb7e780-dbcd-11e9-89fb-77ed0ef5a02c.png)

**Comment by iBicha** [comment]
That's a good question. Currently, The youtube player does not offer a parameter to choose the quality.
This can be changed in the code though.

There are three types of `Stream`s that can be downloaded. Video only, Audio only, and "Muxed" (both)

By default, we play the highest quality of the Muxed stream available. The reason for this is because of easier management, and more predictable file format (it's possible to download audio or video streams that Unity is not capable of decoding and playing). Note that the highest qualities are separated audio and video streams.

You can change how this works by changing the [YoutubePlayer](https://github.com/iBicha/UnityYoutubePlayer/blob/45dce47237035db85dd21eecbcec5fa0ee293cae/Assets/YoutubePlayer/Scripts/YoutubePlayer.cs#L65)

**Comment by MosesQIU** [comment]
How to change i don't really understand??

**Comment by ojy999** [comment]
Need  help on this too.
Seems like 720p is the highest quality it choses, not higher ones

**Comment by ojy999** [comment]
@iBicha I kinda figured out what you meant by changing the code, but the quality is still not the highest. Any solutions? Thank you.
![image](https://user-images.githubusercontent.com/58834355/97151922-24d94f80-17ab-11eb-9c8d-4cb93b8fb104.png)

**Comment by iBicha** [comment]
With the new package v1.1.0, you can specify the quality of the stream, based on `youtube-dl`'s format selection https://github.com/ytdl-org/youtube-dl#format-selection-examples
You can pass the format to the play video
```
var url = "https://www.youtube.com/watch?v=1PuGuqpHQGo";
// Download best format available but no better than 480p
var options = new YoutubeDlOptions("best[height<=480]");
await youtubePlayer.PlayVideoAsync(url, options);
```

**Comment by iBicha** [comment]
If you want a video that has both audio and video, with highest quality (will usually be 720p) use 
```
var options = new YoutubeDlOptions("best");
await youtubePlayer.PlayVideoAsync(url, options);
```
If you want a video that has both only video, with highest quality use
```
var options = new YoutubeDlOptions("bestvideo");
await youtubePlayer.PlayVideoAsync(url, options);
```

**Comment by mhadji05** [comment]
I m using the legacy project and I cant update it because I will lose a lot of work.
I want to give the option to the user to choose specific quality for example FHD, 4K, etc.
How can i do this with the Legacy project?
