### ISSUE TITLE
Estimated download time?

### ISSUE THREAD

**Issue by hiagomdd** [iBicha/UnityYoutubePlayer#65]
(I do not speak English)
I would like to know if there is a way to show the user the video download time, it's not a problem with the package, but I think this is the best place to ask about it, and a sub-question youtube might not like this right? maybe in the case of a big audience.

**Comment by iBicha** [comment]
> I would like to know if there is a way to show the user the video download time

It's possible, but comes to general download speed and ETA from a url, rather than something specific to this package.
This package uses a [UnityWebRequest](https://github.com/iBicha/UnityYoutubePlayer/blob/719b351c540e4a8ad8dc5052449dc6401179e6eb/Packages/com.ibicha.youtube-player/Runtime/YoutubeDownloader.cs#L15), so it's possible to at least show the progress with https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest-downloadProgress.html.

I don't think I will prioritize this on my side, but I'll keep this open in case someone wanted to pick this feature up and contributes a pull request.

> youtube might not like this right? maybe in the case of a big audience.

Probably not. Obviously this package is to be used without warranty under the "unlicensed" license. For what youtube might or might not like, you should check youtube's TOS.

**Comment by iBicha** [comment]
Closing since this is a feature is not tightly related to the package as I said, but something you would read from the networking library as I mentioned. It's been a few years, I don't think it will be a priority, but a pull request to implement this in a sample is welcome
