### ISSUE TITLE
The byte stream type of the given URL is unsupported.

### ISSUE THREAD

**Issue by INeatFreak** [iBicha/UnityYoutubePlayer#85]
I get two error logs when I start the game.

// First Error Log
WindowsVideoMedia error 0xc00d36c4 while reading https://www.youtube.com/watch?v=sujhUPam60o
Context: MFCreateSourceReaderFromURL
Error details: The byte stream type of the given URL is unsupported.
Track types:

// Second Error Log
VideoPlayer cannot play url : https://www.youtube.com/watch?v=sujhUPam60o
Cannot read file.

Windows 10
UnityEditor 2020.1.0f1

**Comment by Grav8** [comment]
I've made an opsie xd
I was pasting the URL to the "Video Player" component rather than "Youtube Player" script. But the issue is still present.

// First Error Log
WindowsVideoMedia error 0x80004004 while reading https://rr6---sn-c53uxax3vh-btql.googlevideo.com/videoplayback?expire=1653319102&ei=XlGLYtmPBNDYyAXdkJDoDQ&ip=185.30.89.171&id=o-AF8U47cpaIxXMUJO9I4C7uXCSK9zFB_iBDsh2gShFyYP&itag=22&source=youtube&requiressl=yes&mh=kG&mm=31%2C29&mn=sn-c53uxax3vh-btql%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=6&pl=23&initcwndbps=300000&spc=4ocVC9urVml589Tc-YlplqZHryCz&vprv=1&mime=video%2Fmp4&ns=IR-tmTDRyfZfru1zgzOtNbwG&cnr=14&ratebypass=yes&dur=95.364&lmt=1630188045487938&mt=1653297178&fvip=1&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=Sjf5ZJfeww3r4Hox&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANQbJVK7XzRxSnQkSkiQZWMAHZrDHiowrIbm35JAQqD8AiBnJ6mw9yv3xK_ZuKGdQtXQauTeu9KtyHzc4maW7zwyyA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO2LlN5Wqx2zCPUALNnNNs6iss4Y0kxEkfM_727wA9y6AiAHaESNHzVgZvsSbaJu83a2fzkFmPzLmFjqFeMWhwiB_w%3D%3D
Context: IMFSourceReader::WaitForSample in StepAllStreams
Error details: Operation aborted
Track types:
   Audio Track, type: %10%16
   Video Track [1280 x 720], type: H264

// Second Error Log
VideoPlayer cannot play url : https://rr6---sn-c53uxax3vh-btql.googlevideo.com/videoplayback?expire=1653319102&ei=XlGLYtmPBNDYyAXdkJDoDQ&ip=185.30.89.171&id=o-AF8U47cpaIxXMUJO9I4C7uXCSK9zFB_iBDsh2gShFyYP&itag=22&source=youtube&requiressl=yes&mh=kG&mm=31%2C29&mn=sn-c53uxax3vh-btql%2Csn-5go7yne6&ms=au%2Crdu&mv=m&mvi=6&pl=23&initcwndbps=300000&spc=4ocVC9urVml589Tc-YlplqZHryCz&vprv=1&mime=video%2Fmp4&ns=IR-tmTDRyfZfru1zgzOtNbwG&cnr=14&ratebypass=yes&dur=95.364&lmt=1630188045487938&mt=1653297178&fvip=1&fexp=24001373%2C24007246&c=WEB&txp=5432434&n=Sjf5ZJfeww3r4Hox&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANQbJVK7XzRxSnQkSkiQZWMAHZrDHiowrIbm35JAQqD8AiBnJ6mw9yv3xK_ZuKGdQtXQauTeu9KtyHzc4maW7zwyyA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO2LlN5Wqx2zCPUALNnNNs6iss4Y0kxEkfM_727wA9y6AiAHaESNHzVgZvsSbaJu83a2fzkFmPzLmFjqFeMWhwiB_w%3D%3D
Cannot read file.

**Comment by iBicha** [comment]
This is unfortunately a limitation of windows video player specifically.
For example, this link works fine for me on mac. 
Not all videos will work, although most of them do.
See https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html
