### ISSUE TITLE
Server can't be reached anymore

### ISSUE THREAD

**Issue by yamgo2** [iBicha/UnityYoutubePlayer#96]
I'm assuming that since Heroku isn't free anymore, the server doesn't exist anymore. Any chance it will be up again anytime soon?

**Comment by iBicha** [comment]
Update:
- I put the app in maintenance mode a bit, and traffic went down
- When I started it back up and tested it, it was working fine
- It was simply not designed to handle this amount of traffic

**The server will be up at least till the end of January from my side.** 
It is very likely to unresponsive though due to high traffic (I'm seeing the same requests happening a lot, so someone is using this at scale) when this happens, the app consumes too much memory and the whole system crashes.

I could put some effort into caching (the responses for the same requests can be reused, with some redis integration) but maybe it's not worth the effort.

Eventually, I might discontinue this server, and let better solutions take over (like Invidious) which is capable of both being a simple redirect server and and full proxy that streams the video itself.

**Comment by jacattrongnlh** [comment]
Can the server detect overuse and throttle their bandwidth?

**Comment by iBicha** [comment]
> Can the server detect overuse and throttle their bandwidth?

That's a feature that needs implementing, currently it does not do that.
Also, it will not help with scale, if you have lots of users, you still have lots of people who won't have the video load.

**Comment by iBicha** [comment]
The public demo instance is **deleted**.

You will need to either:
- [Host your own server](https://github.com/iBicha/UnityYoutubePlayer#how-do-i-host-my-own-youtube-dl-server)
- Use the local instance (if you're on desktop, and not using IL2CPP)
- Host or use [Invidious Example](https://github.com/iBicha/UnityYoutubePlayer/pull/95/files) ([Invidious](https://invidious.io/))

**Comment by iBicha** [comment]
With version 3.0.0, I've changed the approach to use Invidious. I'll be closing this ticket.
