### ISSUE TITLE
Only works on scripting backend Mono

### ISSUE THREAD

**Issue by Koen-RM** [iBicha/UnityYoutubePlayer#98]
For a project we're required to use IL2CPP but when building using this scripting backend the youtube video's no longer are able to load. 
This is only for the integrated method, using a youtube-dl server still works fine.

**Comment by iBicha** [comment]
Thanks for reporting.

This is the same as #79 unfortunately there's no workaround. See https://github.com/iBicha/UnityYoutubePlayer/issues/79#issuecomment-1310621195

The issue was addressed [here](https://github.com/iBicha/UnityYoutubePlayer/pull/94/files), but it was not released in a new package version yet

**Comment by iBicha** [comment]
com.ibicha.youtube-player (2.0.2) pubslihed containing the "fix"
